"""
Alembic Migration Environment

Purpose
-------
Wires Alembic's autogenerate/migration runner to this project's SQLAlchemy Base and DATABASE_URL.

Responsibilities
-----------------
- Import app.db.base.Base and app.db.models (so every model is registered on Base.metadata).
- Set target_metadata = Base.metadata for autogenerate.
- Read the DB URL from app.config.settings instead of a hardcoded value.

Interacts With
--------------
- db/base.py, db/models/__init__.py -> supply target_metadata.
- config.py -> DATABASE_URL.

NOTE: assetflow_schema.sql is the authoritative source of truth (ENUM
types, the booking GiST EXCLUDE constraint, the asset_tag/status-history
triggers, and the dashboard views - none of which autogenerate can express
reliably). The initial migration (0001_initial) therefore op.execute()s
that raw file directly instead of being autogenerated. Alembic is wired
here so that *subsequent* schema changes can use --autogenerate against a
database that was bootstrapped from 0001_initial, with the diff reviewed
for parity against Base.metadata before being committed.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from app.config import settings
from app.db.base import Base
from app.db import models  # noqa: F401  (ensures all models are registered on Base.metadata)

# Alembic Config object, providing access to values in alembic.ini.
config = context.config

# Interpret the config file for Python logging, if a logging section is present.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override the DB URL baked into alembic.ini with the one from application
# settings, so a single DATABASE_URL (in .env) drives both the app and migrations.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (no live DB connection) - emits SQL to stdout/a script."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection) -> None:
    """Shared migration-running logic, invoked with a live (sync-facing) connection."""
    context.configure(connection=connection, target_metadata=target_metadata, compare_type=True)

    with context.begin_transaction():
        context.run_migrations()


async def _run_async_migrations() -> None:
    """
    Create an AsyncEngine (DATABASE_URL uses the asyncpg driver) and run
    migrations through `run_sync`, since Alembic's migration runner itself
    is synchronous.
    """
    connectable: AsyncEngine = create_async_engine(
        config.get_main_option("sqlalchemy.url"),
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (with a live DB connection)."""
    asyncio.run(_run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()