"""initial schema - applies assetflow_schema.sql verbatim

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-12

Purpose
-------
Bootstraps the entire AssetFlow schema (17 tables, 13 ENUM types, the
resource_bookings GiST EXCLUDE constraint, the asset_tag/updated_at/
status-history triggers, and the v_* dashboard views) in one shot.

This is NOT autogenerated. assetflow_schema.sql is authored by hand and
uses several Postgres features SQLAlchemy's autogenerate cannot express
reliably (CREATE TYPE ... AS ENUM, GiST EXCLUDE USING, PL/pgSQL trigger
functions, CREATE VIEW, a standalone SEQUENCE). So instead of translating
that file into `op.create_table()` calls that could silently drift from
it, this migration executes the file directly and is treated as the
single source of truth for revision 0001. Any *later* schema change should
be a normal autogenerated revision on top of this one.
"""

from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

# The raw schema lives alongside this migration so it travels with the
# repo/migration history rather than depending on a path outside alembic/.
_SCHEMA_SQL_PATH = Path(__file__).resolve().parent.parent / "sql" / "assetflow_schema.sql"


def upgrade() -> None:
    """Execute assetflow_schema.sql verbatim against the target database."""
    sql_text = _SCHEMA_SQL_PATH.read_text(encoding="utf-8")
    # A single op.execute() call with the whole (semicolon- and
    # dollar-quote-containing) script is intentional: splitting it into
    # per-statement op.execute() calls would break the PL/pgSQL function
    # bodies (set_updated_at, generate_asset_tag, log_asset_status_change),
    # which contain their own internal semicolons inside $$ ... $$ blocks.
    # Postgres's own multi-statement (simple query) protocol already
    # parses those correctly, so the whole file is sent as one batch.
    op.execute(sql_text)


def downgrade() -> None:
    """Drop everything created by upgrade() by dropping and recreating the public schema."""
    op.execute("DROP SCHEMA public CASCADE;")
    op.execute("CREATE SCHEMA public;")